In [1]:
import pandas as pd

df = pd.read_csv("../../data/results_test1.csv")
df

,conv_id,model_id,request_id,request,reference,response,reformulation,score
0,625,mistral-large-2411,514,y a t il des cultures de safran en france?,"Oui, on trouve des safraniers dans une quarant...","Oui, il y a des cultures de safran en France. ...","Oui, on trouve des safraniers dans plusieurs r...",390.000000
1,629,lfm-40b,514,y a t il des cultures de safran en france?,"Oui, on trouve des safraniers dans une quarant...","Oui, il y a des cultures de safran en France, ...","Oui, on trouve des safraniers dans une quarant...",73.333333
2,1023,mistral-saba,6118,Dis-moi qui siège au trône d'Angleterre ?,"Le monarque actuel est le roi Charles III, dep...","En 2023, le monarque régnant du Royaume-Uni, q...","Le monarque actuel est le roi Charles III, dep...",38.095238
3,1031,llama-3.1-nemotron-70b-instruct,6118,Dis-moi qui siège au trône d'Angleterre ?,"Le monarque actuel est le roi Charles III, dep...",Le roi actuellement au trône d'Angleterre est ...,"Le monarque actuel est le roi Charles III, dep...",19.047619
4,1491,ministral-8b-instruct-2410,557,Combien de communes comporte la Métropole de G...,49 communes. Grenoble Alpes Métropole regroupe...,La Métropole de Grenoble est une collectivité ...,Grenoble Alpes Métropole regroupe 45 communes....,114.285714
...,...,...,...,...,...,...,...,...
65,15002,gemma-2-9b-it,7614,"J'ai un caractère ""1"" qui est transformé en 49...","Si le caractère ""1"" a été encodé par la valeur...",La table de correspondance utilisée est probab...,"Si le caractère ""1"" a été encodé par la valeur...",76.190476
66,15004,mistral-small-24b-instruct-2501,7614,"J'ai un caractère ""1"" qui est transformé en 49...","Si le caractère ""1"" a été encodé par la valeur...","Pour comprendre comment le caractère ""1"" est t...","Si le caractère ""1"" a été encodé par la valeur...",428.571429
67,15964,llama-3.1-405b,7677,Qui est Philippe Glass ?,"Philip Glass, né le 31 janvier 1937 à Baltimor...","Philip Glass, né le 31 janvier 1935 à Baltimor...","Philip Glass, né le 31 janvier 1935 à Baltimor...",210.465116
68,17292,gemini-1.5-pro-002,3293,qu'est ce que SCORM,"SCORM, pour anglais : Sharable Content Object ...",SCORM est un acronyme pour **Sharable Content ...,"SCORM, pour anglais : Sharable Content Object ...",663.636364
69,17293,mistral-small-24b-instruct-2501,3293,qu'est ce que SCORM,"SCORM, pour anglais : Sharable Content Object ...","SCORM, qui signifie **Sharable Content Object ...","SCORM, pour anglais : Sharable Content Object ...",621.212121

In [4]:
df.groupby("model_id")["score"].describe().sort_values("mean")

,count,mean,std,min,25%,50%,75%,max
model_id,,,,,,,,
chocolatine-2-14b-instruct-v2.0.3-q8,2.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
c4ai-command-r-08-2024,1.0,11.111111,NaN,11.111111,11.111111,11.111111,11.111111,11.111111
llama-3.1-nemotron-70b-instruct,1.0,19.047619,NaN,19.047619,19.047619,19.047619,19.047619,19.047619
qwen2.5-coder-32b-instruct,2.0,22.222222,15.713484,11.111111,16.666667,22.222222,27.777778,33.333333
gpt-4o-2024-08-06,2.0,22.549020,15.251323,11.764706,17.156863,22.549020,27.941176,33.333333
mistral-saba,1.0,38.095238,NaN,38.095238,38.095238,38.095238,38.095238,38.095238
gemma-2-9b-it,2.0,67.507003,12.280286,58.823529,63.165266,67.507003,71.848739,76.190476
llama-3.1-405b,4.0,83.489083,86.698924,27.272727,28.246753,48.109244,103.351573,210.465116
mistral-nemo-2407,1.0,100.000000,NaN,100.000000,100.000000,100.000000,100.000000,100.000000
claude-3-5-sonnet-v2,4.0,116.071429,165.476190,33.333333,33.333333,33.333333,116.071429,364.285714
gemini-2.0-flash-exp,3.0,117.243473,148.661594,29.508197,31.420765,33.333333,161.111111,288.888889
lfm-40b,5.0,119.449217,143.270536,33.333333,33.333333,73.333333,84.905660,372.340426
gpt-4o-mini-2024-07-18,4.0,160.232143,91.421193,27.500000,135.875000,196.000000,220.357143,221.428571
mixtral-8x22b-instruct-v0.1,2.0,167.613636,134.189582,72.727273,120.170455,167.613636,215.056818,262.500000
ministral-8b-instruct-2410,2.0,167.781155,75.653978,114.285714,141.033435,167.781155,194.528875,221.276596
claude-3-7-sonnet,1.0,181.818182,NaN,181.818182,181.818182,181.818182,181.818182,181.818182
deepseek-v3-chat,6.0,200.991400,223.887106,14.705882,59.375000,163.194444,198.722222,629.520295
llama-3.3-70b,3.0,207.420113,301.478685,11.111111,33.857442,56.603774,305.574614,554.545455
mistral-small-3.1-24b,1.0,235.793358,NaN,235.793358,235.793358,235.793358,235.793358,235.793358
mistral-small-24b-instruct-2501,5.0,249.433834,266.043865,11.111111,33.333333,152.941176,428.571429,621.212121
phi-4,5.0,266.262626,420.304960,11.111111,33.333333,100.000000,177.777778,1009.090909
mixtral-8x7b-instruct-v0.1,2.0,358.428571,92.732004,292.857143,325.642857,358.428571,391.214286,424.000000
gemini-2.0-flash-001,1.0,478.571429,NaN,478.571429,478.571429,478.571429,478.571429,478.571429
gemini-1.5-pro-002,2.0,591.077441,102.613812,518.518519,554.797980,591.077441,627.356902,663.636364
hermes-3-llama-3.1-405b,2.0,594.444444,54.997194,555.555556,575.000000,594.444444,613.888889,633.333333
mistral-large-2411,4.0,2861.555556,5361.173660,22.222222,106.055556,262.000000,3017.500000,10900.000000
llama-3.1-70b,2.0,9955.555556,14063.568204,11.111111,4983.333333,9955.555556,14927.777778,19900.000000

In [5]:
df.groupby("request")["score"].describe().sort_values("mean")

,count,mean,std,min,25%,50%,75%,max
request,,,,,,,,
Combien y'a t'il de lettres dans le mot alimentaires ?,6.0,9.259259,4.536092,0.000000,11.111111,11.111111,11.111111,11.111111
réponds a cette charade\r\nMon premier n'est pas haut....\r\n \r\nMon second c'est ce que portent les moutons sur eux.\r\n\r\nMon tout est un mammifère qui vit dans l'eau.,2.0,13.235294,2.079726,11.764706,12.500000,13.235294,13.970588,14.705882
combien font 4+4+4,2.0,16.666667,23.570226,0.000000,8.333333,16.666667,25.000000,33.333333
Dis-moi qui siège au trône d'Angleterre ?,2.0,28.571429,13.468701,19.047619,23.809524,28.571429,33.333333,38.095238
"Isabelle bénéficie d'un salaire mensuel net de 1500 euros. Son loyer s'élève à 280 euros tous les mois. Chaque trimestre, elle consacre 1300 euros à la nourriture. Sur une année, elle parvient à épargner 3600 euros. Sachant que tous les semestres, elle envoie 520 euros à sa famille, combien lui reste-t-il d'euros à la fin de chaque mois pour l'habillement et les loisirs ?",1.0,29.508197,NaN,29.508197,29.508197,29.508197,29.508197,29.508197
Combien de « r » dans « strawberry »,2.0,50.000000,32.141217,27.272727,38.636364,50.000000,61.363636,72.727273
Est-ce qu'il y a de la neige dans les Vosges ?,1.0,58.823529,NaN,58.823529,58.823529,58.823529,58.823529,58.823529
combien d'heures sépare la france de la chine,2.0,70.754717,20.012456,56.603774,63.679245,70.754717,77.830189,84.905660
Fais la liste des premiers ministres sous le président Macron,2.0,82.500000,77.781746,27.500000,55.000000,82.500000,110.000000,137.500000
"Donne moi une phrase qui a du sens, de 3 mots, dont chaque mots a le nombre de lettres de chaque chiffre du nombre 234, dans l’ordre",13.0,83.760684,147.378700,22.222222,33.333333,33.333333,33.333333,555.555556
Quel est le poste actuel de François Bayrou ?,2.0,110.294118,60.312049,67.647059,88.970588,110.294118,131.617647,152.941176
"Qui à écrit ""L'insurrection qui vient ?""",2.0,144.444444,62.853936,100.000000,122.222222,144.444444,166.666667,188.888889
Quel est le plus grand nombre entre 3.9 et 3.11,2.0,150.000000,196.418550,11.111111,80.555556,150.000000,219.444444,288.888889
Alice a 4 soeurs et 1 frère. Combien de soeurs a le frère d’Alice ?,2.0,160.714286,186.878221,28.571429,94.642857,160.714286,226.785714,292.857143
Combien de communes comporte la Métropole de Grenoble,2.0,167.857143,75.761441,114.285714,141.071429,167.857143,194.642857,221.428571
Quels sont les numéros des épisodes de la partie 3 de la saison 6 de cobra Kai ?,2.0,168.000000,48.083261,134.000000,151.000000,168.000000,185.000000,202.000000
Qui est Philippe Glass ?,1.0,210.465116,NaN,210.465116,210.465116,210.465116,210.465116,210.465116
y a t il des cultures de safran en france?,2.0,231.666667,223.917147,73.333333,152.500000,231.666667,310.833333,390.000000
"J'ai un caractère ""1"" qui est transformé en 49. Quelle est la table de correspondance utilisée ?",2.0,252.380952,249.170961,76.190476,164.285714,252.380952,340.476190,428.571429
"bonjour, comment s'appelle la mère de francois mitterand",1.0,262.500000,NaN,262.500000,262.500000,262.500000,262.500000,262.500000
Qui a inventé le Vendée globe ?,2.0,296.808511,106.818258,221.276596,259.042553,296.808511,334.574468,372.340426
Quand a été creee la bastide de Monsegur en gironde,2.0,298.000000,178.190909,172.000000,235.000000,298.000000,361.000000,424.000000
Combien d'habitants en France métropolitaine ?,2.0,368.181818,263.557982,181.818182,275.000000,368.181818,461.363636,554.545455
Que signifie l'expression beau comme une girafe ?,2.0,421.428571,80.812204,364.285714,392.857143,421.428571,450.000000,478.571429
Quand a été mise en service le métro d'Athènes ?,2.0,426.666667,292.270803,220.000000,323.333333,426.666667,530.000000,633.333333
détaillez le format ISO 8601,2.0,432.656827,278.406987,235.793358,334.225092,432.656827,531.088561,629.520295
qui a le meilleur son entre le vynil et le cd,1.0,518.518519,NaN,518.518519,518.518519,518.518519,518.518519,518.518519
Combien y a-t-il de livres sur fondation répond en quelques mots ?,2.0,554.545455,642.824347,100.000000,327.272727,554.545455,781.818182,1009.090909
qu'est ce que SCORM,2.0,642.424242,29.998470,621.212121,631.818182,642.424242,653.030303,663.636364
est-ce que le revenu de solidarité active (RSA) est rétroactif ?\r\n,2.0,15400.000000,6363.961031,10900.000000,13150.000000,15400.000000,17650.000000,19900.000000